### ISSUE TITLE
Syncthing icon should rotate during an upload

### ISSUE THREAD

**Issue by Karol-G** [kozec/syncthing-gtk#400]
I think when uploading new files to your syncthing network or when files are pulled from your syncthing device and it is the only one online currently, the syncthing icon should rotate to indicate the upload. So you know not to turn off your device or etc.

**Comment by kozec** [comment]
If I remember correctly, Syncthing doesn't report file being uploaded, so this is most likely not possible.

**Comment by CookingCookie** [comment]
In the web gui it is shown when files are being send to other devices. Is it not possible to extract that information? (I have hardly any programming skills so I can't tell if something like that is possible)

**Comment by canton7** [comment]
FWIW SyncTrayzor rotates the icon whenever there's unbound or outbound traffic. So it catches file uploads, but also catches index exchanges.
