### ISSUE TITLE
Notification area icon

### ISSUE THREAD

**Issue by shawn1thompson** [kozec/syncthing-gtk#543]
Icon doesn't show properly in notification area, i.e., top-right of desktop. It only shows a gray rectangle with a crossed out circle on it.

**Comment by kozec** [comment]
> It only shows a gray rectangle with a crossed out circle on it.

If it doesn't looks like this ![icon](https://raw.githubusercontent.com/syncthing/syncthing-gtk/master/icons/16x16/status/si-syncthing-black-0.png), post a screenshot. If it does, that's the icon :)

**Comment by shawn1thompson** [comment]
![notification-icon](https://user-images.githubusercontent.com/32218754/70642578-115dde00-1c05-11ea-8acd-9db717d84edb.png)

**Comment by shawn1thompson** [comment]
The title bar seems to be missing an icon as well:
![title-bar](https://user-images.githubusercontent.com/32218754/71484131-68041400-27d0-11ea-9ae6-574f357f933d.png)

**Comment by shawn1thompson** [comment]
No longer using Elementary and unable to troubleshoot.
