### ISSUE TITLE
Move to python3.

### ISSUE THREAD

**Issue by advaithm** [kozec/syncthing-gtk#559]
Python 2 has reached the end of life and will no longer be receiving updates. many distributions no longer ship with python 2 hence moving to python 3 will be beneficial for security and maintainability of the project.

i don't mind helping with porting the python 2 sections to python3.

**Comment by hutson** [comment]
@advaithm please see #487 and #546

**Comment by advaithm** [comment]
So there Are no plans for it? It's already been dropped in opensuse tumbleweed it'll be dropped soon in leap

**Comment by Salamandar** [comment]
You can try the Python3 branch of my fork : https://github.com/Salamandar/syncthing-gtk
Please open issues for any problems you have.

**Comment by advaithm** [comment]
i started using the web gui so i no longer need this
