### ISSUE TITLE
Daemon not downloading. Windows 10

### ISSUE THREAD

**Issue by deobbed** [kozec/syncthing-gtk#561]
I cant get syncthing to download the daemon, no idea why.

![syncthing-gtk_VebB1Euia5](https://user-images.githubusercontent.com/62348672/88213056-8348dc00-cc58-11ea-959c-acea80f76a1c.png)

**Comment by sunbunbird** [comment]
same issue for me today.

i checked the source code, it appears to be failing on a call to this method/function:

_cb_read_latest

although i am not sure which call that might be.

method is in stdownloader.py:

                        if self.dll_url is None:
                                raise Exception("No release to download")
                except Exception as e:
                        log.exception(e)
                        self.emit("error", e,
                                _("Failed to determine latest Syncthing version."))
                        return



not a dev, so would have trouble debugging further.  i am going to look for alternatives for getting this set up on windows so i can start using syncthing.

**Comment by kozec** [comment]
Seems to work here. Do you have something like company firewall or proxy server that needs to be used?

**Comment by pakar** [comment]
Having the same thing here.. First install on a Windows 10 system.

C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe -v -d
D UIBuilder     Enabled: header_bar
D UIBuilder     Enabled: is_windows
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file .\app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'is_windows', u'header_bar'])
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: traditional_header
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Removed 'property' by attribute: !is_windows
D UIBuilder     Removed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
I StatusIcon    Using backend StatusIconGTK3 (primary)
D Daemon        Reading syncthing config C:\Users\pakar\AppData\Local\syncthing\config.xml
I Wizard        Searching for syncthing binary...
I Wizard         ... C:\Program Files\Syncthing\syncthing.exe
I Wizard         ... ./syncthing.exe
I Wizard         ... C:\Users\pakar/.local/bin\syncthing.exe
I Wizard         ... C:\Users\pakar\AppData\Local\syncthing\syncthing.exe
I Wizard         ... c:/Program Files/syncthing\syncthing.exe
I Wizard         ... c:/Program Files (x86)/syncthing\syncthing.exe
I Wizard         ... C:\Users\pakar\AppData\Local\syncthing\syncthing.exe
I Wizard         ... .\syncthing.exe
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.12.24
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.12.25
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.13
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.13.6
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.13.10
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.18
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.44
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.47
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.50
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.51
V StDownloader  STDownloader: Got newer compatible Syncthing version v0.14.53
V StDownloader  STDownloader: Got newer compatible Syncthing version v1.0.1
V StDownloader  STDownloader: Got newer compatible Syncthing version v1.2.2
V StDownloader  STDownloader: Got newer compatible Syncthing version v1.3.3
V StDownloader  STDownloader: Latest compatible Syncthing version: v1.3.3
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.8.0-rc.2
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.8.0-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.7.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.7.0
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.7.0-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0-rc.5
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0-rc.4
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0-rc.3
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0-rc.2
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.6.0-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.5.0
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.5.0-rc.2
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.5.0-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.2
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.2-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.1-rc.3
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.1-rc.2
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.1-rc.1
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.11
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.10
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.9
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.8
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.7
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.5
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.4
V StDownloader  STDownloader: Ignoring too new Syncthing version: v1.4.0-rc.3
E StDownloader  No release to download
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\stdownloader.py", line 213, in _cb_read_latest
Exception: No release to download

**Comment by kozec** [comment]
Can either of you try it now?

**Comment by sunbunbird** [comment]
just opened syncthingGTK, download proceeded, but I canceled the download
since I am using synctrayzor at this point and did not want to cause any
interference with that as far as configs might go

**Comment by sunbunbird** [comment]
hi, just fyi i am going to try syncthinggtk right now, i do not like synctrayzor's gui very much tbh.

i suppose i will learn syncthing proper at some point, but for my windows machine i do not want to touch the commandline if at all possible

**Comment by heX16** [comment]
same issue for me.

**Comment by awdav** [comment]
Some thing happening for me again too. Windows 10 client not updating syncthing daemon version.

**Comment by kozec** [comment]
Update issue should be fixed now.

**Comment by josh-hemphill** [comment]
This issue seems to have reappeared. At least for me.
